import lighthouse from 'lighthouse';
import * as chromeLauncher from 'chrome-launcher';
import {startServer,save} from './test-server.mjs';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const args=process.argv.slice(2),only=args.includes('--after-only'),root=args.find(a=>!a.startsWith('--'))||'dist';
const nestedBaseline='cache-baseline/LCA_WEBSITE_v101_1_5I_DEPLOYABLE 2';
if(!only&&!fs.existsSync('cache-baseline/index.html')&&!fs.existsSync(nestedBaseline+'/index.html'))execFileSync('python3',['-c',"import zipfile; zipfile.ZipFile('reference/baseline-v101.1.5I.zip').extractall('cache-baseline')"]);
const before=only?null:await startServer(fs.existsSync('cache-baseline/index.html')?'cache-baseline':nestedBaseline,8787),after=await startServer(root,8793);
const results=[];fs.mkdirSync('evidence/lighthouse',{recursive:true});
try{for(const [release,server] of [...(before?[['before',before]]:[]),[only?'artifact':'after',after]])for(const [route,slug] of [['/','home'],['/services','services'],['/e-props-dealer-support','eprops'],['/rotax-engine-systems-support','engine'],['/rotax-gearbox-propeller-vibration','vibration'],['/rotax-installation-review','installation'],['/light-sport-prebuy-evaluation','prebuy'],['/support-request','form']].filter(([route])=>!process.env.LCA_PERF_ROUTES||process.env.LCA_PERF_ROUTES.split(',').includes(route))){
 const chrome=await chromeLauncher.launch({chromePath:process.env.LCA_CHROMIUM_EXECUTABLE,chromeFlags:['--headless','--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],logLevel:'silent'});
 try{const run=await lighthouse(server.url+route,{port:chrome.port,output:'json',logLevel:'error',onlyCategories:['performance','accessibility','best-practices','seo'],throttlingMethod:'simulate',formFactor:'mobile',screenEmulation:{mobile:true,width:412,height:823,deviceScaleFactor:1.75,disabled:false}});const report=run.lhr;fs.writeFileSync(`evidence/lighthouse/${release}-${slug}.json`,JSON.stringify(report));const r={release,route,lighthouse_version:report.lighthouseVersion,chromium:report.environment.hostUserAgent,configuration:report.configSettings,performance:Math.round(report.categories.performance.score*100),accessibility:Math.round(report.categories.accessibility.score*100),seo:Math.round(report.categories.seo.score*100),lcp_ms:report.audits['largest-contentful-paint'].numericValue,cls:report.audits['cumulative-layout-shift'].numericValue,tbt_ms:report.audits['total-blocking-time'].numericValue,transfer_bytes:report.audits['total-byte-weight'].numericValue,errors:report.runtimeError||null};results.push(r);console.log(JSON.stringify({release,route,performance:r.performance,lcp_ms:Math.round(r.lcp_ms),cls:r.cls,bytes:r.transfer_bytes}))}finally{await chrome.kill()}
 }}finally{before?.stop();after.stop();save(process.env.LCA_PERF_ROUTES?'evidence/affected-performance.json':only?'evidence/artifact-performance.json':'evidence/performance.json',{method:'One mobile lab run per route/release, same local Pages-route/header model, browser/configuration. Not field p75 or INP measurements.',root,runs:results})}
if(only&&results.some(r=>r.errors||r.performance<95||r.accessibility<98||r.seo<100||(['/','/e-props-dealer-support'].includes(r.route)&&r.lcp_ms>1800)||r.cls>0.05||r.tbt_ms>100))process.exitCode=1;
