import {chromium,firefox,webkit} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {startServer,save} from './test-server.mjs';
const root=process.argv[2]||'dist',prefix=process.argv[3]||'browser';
const server=await startServer(root,8788,{wrangler:true});
const routes=JSON.parse(fs.readFileSync('evidence/routes.json'));
const result={environment:'Cloudflare Wrangler Pages local static-asset engine; loopback interface-display shim; not deployed production',root,engines:[],routes:[],layouts:[],axe:[],forms:[],manual:[],console_errors:[],failures:[],limits:['No physical iPhone/Android, screen reader, actual inbox delivery, field Core Web Vitals or five-person owner study']};
function check(condition,label){if(!condition)throw new Error(label)}
async function chain(path){let target=server.url+path,steps=[];for(let i=0;i<8;i++){const r=await fetch(target,{redirect:'manual'});steps.push({url:new URL(target).pathname+new URL(target).search,status:r.status,location:r.headers.get('location'),cache:r.headers.get('cache-control')});if(r.status<300||r.status>=400)return steps;target=new URL(r.headers.get('location'),target).href}throw new Error('Redirect loop: '+path)}
try{
 for(const r of routes){for(const p of [r.route,r.route==='/'?'/index.html':r.route+'.html',...(r.route==='/'?[]:[r.route+'/'])]){const steps=await chain(p);check(steps.at(-1).status===200,'Route failed '+p);check(steps.length<=2,'Multiple path redirects '+p);result.routes.push({requested:p,steps})}}
 for(const p of ['/e-props-usa-dealer-support','/e-props-usa-dealer-support.html','/rotax-912-rubber-replacement','/prebuy']){const steps=await chain(p);check(steps.length===2&&steps.at(-1).status===200,'Legacy alias '+p);result.routes.push({requested:p,steps})}
 for(const p of ['/unknown-release-test-route','/_headers','/_redirects']){const steps=await chain(p);check(steps.at(-1).status===404,'Need real 404 '+p);result.routes.push({requested:p,steps})}
 const card=await chain('/card?source=qr');check(card.length===1&&card[0].status===200,'QR canonical loop');result.routes.push({requested:'/card?source=qr',steps:card});
 const assets=JSON.parse(fs.readFileSync('evidence/asset-map.json'));const v=await fetch(server.url+assets['assets/downloads/joseph-helminiak-lima-charlie-aero.vcf']);check(v.headers.get('content-type').startsWith('text/vcard'),'vCard MIME');check(v.headers.get('content-disposition').includes('attachment'),'vCard download');const vcf=await v.text();check(vcf.match(/^TEL[^:]*:(.+)$/m)?.[1].replace(/\D/g,'')==='19803821344'&&vcf.includes('support@limacharlieaero.com')&&vcf.includes('Helminiak'),'vCard content');
 const css=await fetch(server.url+assets.css);check(css.headers.get('cache-control').includes('immutable'),'Asset cache header');const html=await fetch(server.url+'/');check(!html.headers.get('cache-control')?.includes('immutable'),'HTML must revalidate');check(html.headers.get('x-content-type-options')==='nosniff','Security header');result.manual.push({test:'vCard content, MIME, download; security headers; hash asset caching and HTML revalidation',status:'PASS'});
 for(const [name,type] of Object.entries({chromium,firefox,webkit})){
  let browser;
  try{browser=await type.launch({headless:true,timeout:15000,...(name==='chromium'&&process.env.LCA_CHROMIUM_EXECUTABLE?{executablePath:process.env.LCA_CHROMIUM_EXECUTABLE}:{}),...(name==='firefox'?{env:{...process.env,MOZ_DISABLE_CONTENT_SANDBOX:'1'}}:{})});result.engines.push({name,version:browser.version(),status:'PASS',emulated:true});console.log('Checking '+name+' '+browser.version())}catch(e){result.engines.push({name,status:'BLOCKED',reason:String(e).slice(0,2200)});continue}
  const context=await browser.newContext({reducedMotion:'reduce'});await context.route('https://formspree.io/**',r=>r.abort());const page=await context.newPage();page.on('pageerror',e=>result.console_errors.push({engine:name,error:String(e)}));
  const testRoutes=name==='chromium'?routes:routes.filter(r=>['/','/support-request','/e-props-dealer-support','/light-sport-prebuy-evaluation','/rotax-turbocharger-notice','/faq','/card'].includes(r.route));
  for(const route of testRoutes){for(const width of [320,375,390,768,1024,1440]){await page.setViewportSize({width,height:width<768?844:900});await page.goto(server.url+route.route);await page.evaluate(async()=>{for(const i of document.images){i.scrollIntoView({block:'center'});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));await Promise.race([i.decode().catch(()=>{}),new Promise(r=>setTimeout(r,2500))])};window.scrollTo(0,0)});const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,broken:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),h1:document.querySelectorAll('h1').length}));check(metrics.scrollWidth<=width+1,'Overflow '+name+' '+route.route+' '+width);check(metrics.broken.length===0,'Broken image '+route.route);check(metrics.h1===1,'Heading '+route.route);result.layouts.push({engine:name,route:route.route,width,...metrics})}
   if(name==='chromium'){await page.setViewportSize({width:390,height:844});await page.goto(server.url+route.route);const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();result.axe.push({route:route.route,violations:a.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),incomplete:a.incomplete.map(v=>({id:v.id,nodes:v.nodes.length}))});check(a.violations.length===0,'Axe violation '+route.route+': '+a.violations.map(v=>v.id).join(','))}
  }
  await page.setViewportSize({width:390,height:844});await page.goto(server.url+'/support-request');const first=await page.locator('#support-name').boundingBox();check(first.y+first.height<844,'First field below fold');const legend=await page.locator('legend').boundingBox();check(legend.y<844,'Form heading below fold');result.manual.push({engine:name,test:'390×844 form introduction and first field visible without scroll',status:'PASS',first_field:first});
  await page.setViewportSize({width:1366,height:768});await page.goto(server.url+'/support-request');const desktop=await page.locator('#support-name').boundingBox();check(desktop.y+desktop.height<768,'Desktop first field below fold');
  await page.setViewportSize({width:844,height:390});for(const route of ['/','/support-request','/card']){await page.goto(server.url+route);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Landscape overflow '+route)}
  await page.setViewportSize({width:320,height:844});await page.goto(server.url+'/support-request');await page.evaluate(()=>{const all=[...document.querySelectorAll('body,body *')].map(el=>[el,getComputedStyle(el).fontSize]);for(const [el,size] of all)el.style.fontSize=(parseFloat(size)*2)+'px'});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'200% text overflow');result.manual.push({engine:name,test:'200% computed text enlargement at 320 CSS px and 844×390 landscape',status:'PASS',method:'CSS font enlargement; not a physical-device or OS browser-zoom test'});
  await page.setViewportSize({width:390,height:844});await page.goto(server.url+'/');await page.keyboard.press('Tab');check(await page.locator('.skip').evaluate(el=>el===document.activeElement),'Skip link first');await page.keyboard.press('Enter');check(await page.locator('main').evaluate(el=>el===document.activeElement),'Skip target focus');await page.locator('[data-menu]').click();check(await page.locator('[data-menu]').getAttribute('aria-expanded')==='true','Menu open');await page.keyboard.press('Escape');check(await page.locator('[data-menu]').getAttribute('aria-expanded')==='false','Menu escape');check(await page.locator('[data-menu]').evaluate(el=>el===document.activeElement),'Menu focus');await page.goto(server.url+'/faq');const question=page.locator('.faq summary').first();await question.focus();await page.keyboard.press('Enter');check(await page.locator('.faq details').first().getAttribute('open')!==null,'FAQ keyboard');result.manual.push({engine:name,test:'Keyboard skip, menu open/Escape/focus, FAQ disclosure; reduced motion with no automatic carousel',status:'PASS'});
  if(name==='chromium'){
   fs.mkdirSync('evidence/screenshots',{recursive:true});for(const [route,slug] of [['/','home'],['/support-request','form'],['/e-props-dealer-support','eprops']])for(const [width,label] of [[390,'mobile'],[1440,'desktop']]){await page.setViewportSize({width,height:width===390?844:900});await page.goto(server.url+route);await page.evaluate(async()=>{for(const i of document.images){i.scrollIntoView({block:'center'});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));await i.decode().catch(()=>{})};window.scrollTo(0,0)});await page.screenshot({path:`evidence/screenshots/${prefix}-${slug}-${label}.png`,fullPage:true})}
   await page.goto(server.url+'/');const contrast=[];for(const sel of ['.button','.hero-credential','.card-link']){const loc=page.locator(sel).first();for(const state of ['normal','hover','focus']){await page.mouse.move(0,0);if(state==='hover')await loc.hover();if(state==='focus')await loc.focus();contrast.push({selector:sel,state,...await loc.evaluate(el=>{const s=getComputedStyle(el);let parent=el,bg=s.backgroundColor;while(bg==='rgba(0, 0, 0, 0)'&&parent.parentElement){parent=parent.parentElement;bg=getComputedStyle(parent).backgroundColor}return {foreground:s.color,background:bg,outline:s.outlineColor,font_size:s.fontSize}})})}}result.contrast=contrast;
   const fpage=await context.newPage();await fpage.unroute('https://formspree.io/**');let requests=[];
   async function setup(path='/support-request',mode='success'){
    await fpage.unroute('https://formspree.io/**');await fpage.route('https://formspree.io/**',async r=>{requests.push({method:r.request().method,body:r.request().postData()});if(mode==='offline')return r.abort('internetdisconnected');if(mode==='timeout')return;const status=mode==='reject'?400:mode==='rate'?429:mode==='server'?500:200;await new Promise(resolve=>setTimeout(resolve,100));await r.fulfill({status,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:mode==='unconfirmed'?JSON.stringify({note:'no acceptance marker'}):JSON.stringify(status===200?{ok:true}:{errors:[{field:'email',message:'Mock provider rejected this email'}]})})});await fpage.goto(server.url+path);requests=[];
   }
   async function fill(method='email') {await fpage.locator('#support-name').fill('Synthetic local release check');await fpage.locator('#support-method').selectOption(method);if(method==='email')await fpage.locator('#support-email').fill('release-check@example.invalid');else await fpage.locator('#support-phone').fill('202-555-0100');await fpage.locator('#support-message').fill('Synthetic local test — no aircraft data.');}
   async function send(){await fpage.locator('button[type=submit]').click();await fpage.locator('#form-status:not([hidden])').waitFor({timeout:20000});}
   await setup();check(await fpage.locator('#support-topic').inputValue()==='','Neutral topic');check(await fpage.locator('#support-urgency').inputValue()==='','Neutral urgency');await send();check(requests.length===0,'Empty form submitted');check(await fpage.locator('#support-name').getAttribute('aria-invalid')==='true','Required field error');result.forms.push({test:'Neutral initial topic/timing and empty validation',status:'PASS',kind:'LOCAL MOCK'});
   for(const [query,method] of [['equipment','email'],['symptom','email'],['service','phone'],['prebuy','email'],['eprops','phone'],['avionics','email'],['notice','phone'],['records','email'],['unsure','email']]){await setup('/support-request?topic='+query);check(await fpage.locator('#support-topic').inputValue()===query,'Prefill '+query);check(await fpage.locator('#topic-prefill').isVisible(),'Prefill visible');check(!fpage.url().includes('?'),'Query retained');await fill(method);await send();check(requests.length===1,'Submission count '+query);check((await fpage.locator('#form-status').textContent()).startsWith('Request submitted.'),'Mock acceptance '+query);check(!requests[0].body.includes('name="n_number"'),'Required tail unexpectedly sent');result.forms.push({test:query+' owner path with '+method+' only, unknown technical details and accepted mock',status:'PASS',kind:'LOCAL MOCK',request_count:requests.length})}
   await setup('/support-request?topic=invalid&name=do-not-copy');check(await fpage.locator('#support-topic').inputValue()==='','Invalid topic accepted');await fill();await fpage.locator('#support-email').fill('invalid-email');await send();check(requests.length===0,'Malformed email sent');result.forms.push({test:'Invalid/stale query and malformed email',status:'PASS',kind:'LOCAL MOCK'});
   for(const mode of ['reject','rate','server','offline','unconfirmed','timeout']){await setup('/support-request',mode);await fill();await send();check(await fpage.locator('#support-message').inputValue()!=='','Data lost after '+mode);check(!((await fpage.locator('#form-status').textContent()).startsWith('Request submitted.')),'False acceptance '+mode);check(!(await fpage.locator('button[type=submit]').isDisabled()),'Retry disabled '+mode);result.forms.push({test:mode+' feedback preserves input without false success',status:'PASS',kind:'LOCAL MOCK'});if(mode==='reject'){await fpage.unroute('https://formspree.io/**');await fpage.route('https://formspree.io/**',r=>r.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'}));await send();check((await fpage.locator('#form-status').textContent()).startsWith('Request submitted.'),'Retry after rejection');result.forms.push({test:'Retry after recoverable rejection',status:'PASS',kind:'LOCAL MOCK'})}}
   await setup();await fill();await fpage.locator('form').evaluate(form=>{form.requestSubmit();form.requestSubmit()});await fpage.locator('#form-status:not([hidden])').waitFor();check(requests.length===1,'Duplicate rapid submit');result.forms.push({test:'Rapid double submit results in one request while pending',status:'PASS',kind:'LOCAL MOCK'});
   await fpage.goto(server.url+'/thank-you');check(!/copy sent|on the board|appointment confirmed|your request has been received/i.test(await fpage.locator('main').innerText()),'False direct confirmation');check(await fpage.evaluate(()=>localStorage.length===0&&sessionStorage.length===0),'Form data storage');result.forms.push({test:'Direct thank-you is neutral; no local/session PII persistence',status:'PASS',kind:'LOCAL'});
   const offline=await browser.newContext({javaScriptEnabled:false});const nojs=await offline.newPage();for(const route of ['/','/support-request','/card']){await nojs.goto(server.url+route);check(await nojs.locator('a[href="tel:+19803821344"]').first().isVisible(),'No-JS call fallback '+route);check(await nojs.locator('main').innerText(),'No-JS content')}await offline.close();result.manual.push({test:'Content, navigation, Call/Text and native form markup without JavaScript',status:'PASS',limit:'Actual native Formspree submission not verified'});
  }
  await context.close();await Promise.race([browser.close(),new Promise(r=>setTimeout(r,3000))]);
 }
 check(result.engines.some(e=>e.name==='chromium'&&e.status==='PASS'),'Chromium unavailable');check(result.console_errors.length===0,'Page script errors');result.status='PASS';
}catch(e){result.status='FAIL';result.failures.push(String(e));console.error(String(e))}finally{save(`evidence/${prefix}-checks.json`,result);fs.writeFileSync(`evidence/${prefix}-wrangler.log`,server.logs());server.stop()}
console.log(JSON.stringify({status:result.status,engines:result.engines.map(e=>({name:e.name,version:e.version,status:e.status})),route_checks:result.routes.length,layout_checks:result.layouts.length,axe_pages:result.axe.length,form_checks:result.forms.length,failures:result.failures}));process.exit(result.status==='PASS'?0:1);
